### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by MarcoCarnevali** [tmergulhao/Ambience#1]
after pod install:

Unable to find a specification for `Ambience`

Thank you!

**Comment by tmergulhao** [comment]
Hey, @MarcoCarnevali! Can you send me a zip of your project or something?

**Comment by MarcoCarnevali** [comment]
Sorry I can't for NDA. But I put pod 'Ambience' on podfile.
Thanks

**Comment by tmergulhao** [comment]
Hey, @MarcoCarnevali. I think you might be able to fix it by 'pod repo update'

Kudos to @marcosgriselli

**Comment by MarcoCarnevali** [comment]
Tha fixed my issue, thank you !!
