### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ergunkocak** [tmergulhao/Ambience#4]
Hello,

First of all thanks for the library 👍 

How can i set opitons titles of AmbienceObject ActionSheet, programmatically? 

I dont want to localize the storyboards. I already have one localization file and all localizations are handled programmaticly in my project.

Best

**Comment by tmergulhao** [comment]
Hey @ergunkocak,

You only have to set the values for the labels:

```
@IBInspectable var invertAvailable : Bool = true
@IBInspectable var invertLabel : String = "Invert"

@IBInspectable var regularAvailable : Bool = true
@IBInspectable var regularLabel : String = "Regular"

@IBInspectable var contrastAvailable : Bool = true
@IBInspectable var contrastLabel : String = "Contrast"

@IBInspectable var autoAvailable : Bool = true
@IBInspectable var autoLabel : String = "Auto"
```
These are variables, so you should do `object.invertLabel = "Dark Mode"`, for example.

See [the object file](https://github.com/tmergulhao/Ambience/blob/master/Ambience/Classes/AmbienceObject.swift)
